### ISSUE TITLE
Support owncloud

### ISSUE THREAD

**Issue by Christophe55** [jancelin/geo-poppy#16]
Bonjour, je suis avec grand intérêt  votre projet, c'est super. 
Ce serait génial d'installer une instance d'owncloud pour le téleversement  des fichiers directement dans le répertoire projet, se serait plus convivial que de jouer avec la console.

**Comment by jancelin** [comment]
Salut,
Merci pour le retour, ça fait plaisir.
Il va y avoir très prochainement un container qui permettra de faire le transfert de fichier de type Owncloud, Mais ce ne sera pas Owncloud car il est trop lourd pour ce simple usage. 
Je pense à une page web qui permettra de glisser déposer les projet qgis et fichier de conf lizmap.
J'ai débroussaillé le sujet avec @MickaelH974

**Comment by jancelin** [comment]
Tu peux essayer ça:
Rajoute à ton docker-compose.yml

```
  cloud:
    image: valentinalexeev/rpi-cloudcmd
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ~:/root
      - /:/mnt/fs
```

et un

```
docker-compose up -d cloud
```
tu trouvera les projets lizmap dans /mnt/fs/home/GeoPoppy, ensuite glissé, déposé , gestion des droits avec la console...
