### ISSUE TITLE
PostgreSQL 11?

### ISSUE THREAD

**Issue by pierrechtux** [jancelin/geo-poppy#63]
Je mets en place un serveur GeoPoppy, et il semble qu'une des requêtes (VIEWs) de la base installée nécessite une version 11 de PostgreSQL.

Il s'agit d'une requête faisant de la moyenne glissante en utilisant une fonction WINDOW de type:
```
  OVER (
  PARTITION BY 
  ORDER BY 
  RANGE BETWEEN x PRECEDING AND y FOLLOWING
```

Cette requête tourne bien sur une instance en PostgreSQL 11, mais se refuse à tourner sur l'instance du GeoPoppy, avec ce message:
```
ERROR:  RANGE PRECEDING is only supported with UNBOUNDED
LIGNE 8 :   RANGE BETWEEN 0.5 PRECEDING AND 0.5 FOLLOWING
```
Et, renseignement pris, cela (RANGE BETWEEN) a été implémenté à partir de PostgreSQL 11.

D'où ma question: est-il question de passer à du PostgreSQL 11 dans GeoPoppy?

**Comment by jancelin** [comment]
c'est en cours de fabrication! bientôt
Le problème est que la version11 n'est disponible que dans la branche expérimentale de debian, j'attendais au moins un depot sid.

Une option temporaire est de mettre à jours le container en postgresql11 et de le sauver.

**Comment by jmarsac** [comment]
Salut Julien,
Tu peux ajouter les dépôts PG ( https://www.postgresql.org/download/linux/debian/ ) à tes sources. C'est ce que j'utilise sans problème

**Comment by jancelin** [comment]
je voudrais bien mais les raspberry Pi ont des processeurs armhf...

dépôts postgresql:
```
 The PostgreSQL apt repository supports the currently supported stable versions of Debian:

    Stretch (9.x)
    Jessie (8.x)
    Wheezy (7.x)

on the following architectures:

    amd64
    i386
    ppc64el
```

depôts debian:
```
Paquet postgresql-11-postgis-2.5
    experimental (misc): Geographic objects support for PostgreSQL 11
    2.5.2+dfsg-1~exp1: amd64 arm64 armel armhf i386 mips mips64el mipsel ppc64el riscv64 s390x x32

```

**Comment by jmarsac** [comment]
@jancelin Oups ! J'avais shunté le pb du processeur ! désolé.

**Comment by jancelin** [comment]
Nouvelle image postgresql11-postgis2.5 à tester, c'est un premier jet.

 j'ai mappé le port 5432 sur le 5435 et linké sur un nouveau dossier /home/pirate/geopoppy/postgresql11 pour ne pas impacter les bases postgresql10 existantes.

@pierrechtux pense à utiliser le bon port (5435) dans pgadmin4 & Qgis.

je n'ai pas la possibilité encore d'intégrer postgresql-11-pgrouting car pas disponible à ce jour dans debian sid ou experimental pour arm (armel).

Voici le bloc à rajouter dans le ```docker-compose.yml```:

```
  db:
    image: jancelin/geopoppy:rpi_postgres11-postgis2.5
    volumes:
      - /home/pirate/geopoppy/postgresql11:/var/lib/postgresql
      - /home/pirate/geopoppy/dbbackups:/backups
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      #- POSTGRES_MULTIPLE_EXTENSIONS=postgis,hstore,postgis_topology
    ports:
      - 5435:5432
    restart: on-failure
    healthcheck:
      test: "exit 0"
```
et lancer un ```docker-compose up db```

>source: https://github.com/jancelin/docker-postgis-rpi/tree/master
