### ISSUE TITLE
New releases et upgrade

### ISSUE THREAD

**Issue by 0b-1** [jancelin/geo-poppy#64]
Bonjour,

Je vois qu'une nouvelle release a été publiée mais je ne parviens pas à mettre à jour  les différentes applications. Quelle est la meilleur approche ? Faut-il re-flasher et reconfigurer ? Ou faut-il aller depuis chaque container lancer des apt ? (essayé mais je ne parviens pas à mettre à jour les applis principales).
Merci par avance.

**Comment by jancelin** [comment]
Salut,

La meilleure approche est de reflasher la carte SD avec la dernière image car l'architecture change pas mal en ce moment.
la solution pour avoir tout ses projets carto et db suite à l'intallation d'une nouvelle image  est de les incorporer dans la sd avant de l'insérer dans le raspberry (pas encore de wiki la dessus):

Donc, après flashage de la carte sd sur pc avec la dernière image  GeoPoppy et avant de l'insérer dans le rpi:

* change le db dump geopoppy.tar (/home/pirate) par le dump de ta base de donnée en .tar, si pas le même nom il faudra le modifier dans le docker-compose.yml POSTGRES_DUMP, et modifier le nom de ta base de donnée dans le docker-compose.yml POSTGRES_DBNAME, idem user POSTGRES_USER

```
 postgis:
    image: jancelin/geopoppy:postgres10-2.4-arm32_1
    restart: unless-stopped
    ports:
      - 5432:5432
    expose:
      - 5432
    entrypoint: >
      bash -c "cp  /home/setup-database.sh / &&
               /docker-entrypoint.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_DBNAME=geopoppy
      - POSTGRES_DUMP=geopoppy.tar
    volumes:
      - /home/pirate/geopoppy/postgresql:/var/lib/postgresql
- /home/pirate:/home
```

* change ensuite le geopoppy.zip (/home/pirate) par ton propre geopoppy.zip contenant tes fichiers qgis, lizmap, ortho,.... pas possible de changer le nom.

* ensuite insère la sd dans le rpi et branche (connect un ecran hdmi pour debug si besoin) pour le premier boot qui va deployer les containers, la db, les projets et configurer le rpi (env 25min).

Pour une utilisation de plusieurs geopoppy, faire cette dernière procedure, éteindre le rpi quand c'est fini, sortir la sd et la remettre dans le pc et utiliser [ça](https://github.com/jancelin/geo-poppy/wiki/4.-Sauvegarde-de-la-SD) pour faire une copie pure et parfaite de la sd et donc la déployer sur d'autres carte sd rapidement. c'est du clonage en résumé.
